In [13]:
import os
print(os.getcwd())

C:\Users\poova\Machine Learning

In [16]:
df = pd.read_csv("insurance_classification/claimants.csv")

In [18]:
import pandas as pd

In [23]:
df = pd.read_csv(r"C:\Users\poova\Machine Learning\insurance_classification\claimants.csv")
df

      CASENUM  ATTORNEY  CLMSEX  CLMINSUR  SEATBELT  CLMAGE    LOSS
0           5         0     0.0       1.0       0.0    50.0  34.940
1           3         1     1.0       0.0       0.0    18.0   0.891
2          66         1     0.0       1.0       0.0     5.0   0.330
3          70         0     0.0       1.0       1.0    31.0   0.037
4          96         1     0.0       1.0       0.0    30.0   0.038
...       ...       ...     ...       ...       ...     ...     ...
1335    34100         1     0.0       1.0       0.0     NaN   0.576
1336    34110         0     1.0       1.0       0.0    46.0   3.705
1337    34113         1     1.0       1.0       0.0    39.0   0.099
1338    34145         0     1.0       0.0       0.0     8.0   3.177
1339    34153         1     1.0       1.0       0.0    30.0   0.688

[1340 rows x 7 columns]

In [22]:
df.head()

   CASENUM  ATTORNEY  CLMSEX  CLMINSUR  SEATBELT  CLMAGE    LOSS
0        5         0     0.0       1.0       0.0    50.0  34.940
1        3         1     1.0       0.0       0.0    18.0   0.891
2       66         1     0.0       1.0       0.0     5.0   0.330
3       70         0     0.0       1.0       1.0    31.0   0.037
4       96         1     0.0       1.0       0.0    30.0   0.038

In [6]:
df.tail()

      CASENUM  ATTORNEY  CLMSEX  CLMINSUR  SEATBELT  CLMAGE   LOSS
1335    34100         1     0.0       1.0       0.0     NaN  0.576
1336    34110         0     1.0       1.0       0.0    46.0  3.705
1337    34113         1     1.0       1.0       0.0    39.0  0.099
1338    34145         0     1.0       0.0       0.0     8.0  3.177
1339    34153         1     1.0       1.0       0.0    30.0  0.688

In [7]:
del df['CASENUM']

In [8]:
df

      ATTORNEY  CLMSEX  CLMINSUR  SEATBELT  CLMAGE    LOSS
0            0     0.0       1.0       0.0    50.0  34.940
1            1     1.0       0.0       0.0    18.0   0.891
2            1     0.0       1.0       0.0     5.0   0.330
3            0     0.0       1.0       1.0    31.0   0.037
4            1     0.0       1.0       0.0    30.0   0.038
...        ...     ...       ...       ...     ...     ...
1335         1     0.0       1.0       0.0     NaN   0.576
1336         0     1.0       1.0       0.0    46.0   3.705
1337         1     1.0       1.0       0.0    39.0   0.099
1338         0     1.0       0.0       0.0     8.0   3.177
1339         1     1.0       1.0       0.0    30.0   0.688

[1340 rows x 6 columns]

In [11]:
df.shape

(1340, 6)

In [12]:
df.dtypes

ATTORNEY      int64
CLMSEX      float64
CLMINSUR    float64
SEATBELT    float64
CLMAGE      float64
LOSS        float64
dtype: object

In [13]:
df.isna().sum()

ATTORNEY      0
CLMSEX       12
CLMINSUR     41
SEATBELT     48
CLMAGE      189
LOSS          0
dtype: int64

In [17]:
df.dropna(inplace=True,ignore_index=True)
df

      ATTORNEY  CLMSEX  CLMINSUR  SEATBELT  CLMAGE    LOSS
0            0     0.0       1.0       0.0    50.0  34.940
1            1     1.0       0.0       0.0    18.0   0.891
2            1     0.0       1.0       0.0     5.0   0.330
3            0     0.0       1.0       1.0    31.0   0.037
4            1     0.0       1.0       0.0    30.0   0.038
...        ...     ...       ...       ...     ...     ...
1091         1     1.0       1.0       0.0    16.0   0.060
1092         0     1.0       1.0       0.0    46.0   3.705
1093         1     1.0       1.0       0.0    39.0   0.099
1094         0     1.0       0.0       0.0     8.0   3.177
1095         1     1.0       1.0       0.0    30.0   0.688

[1096 rows x 6 columns]

In [18]:
df.duplicated().sum()

np.int64(8)

In [20]:
df[df.duplicated()]

      ATTORNEY  CLMSEX  CLMINSUR  SEATBELT  CLMAGE   LOSS
363          1     0.0       1.0       0.0    57.0  3.889
683          0     1.0       1.0       0.0    48.0  1.050
706          1     1.0       1.0       0.0    30.0  0.300
765          0     1.0       1.0       0.0     8.0  0.100
786          1     0.0       1.0       0.0    11.0  0.500
804          0     1.0       1.0       0.0    43.0  8.490
878          0     0.0       1.0       0.0     7.0  0.640
1032         1     0.0       1.0       0.0     0.0  0.440

In [22]:
df.drop_duplicates(inplace=True,ignore_index=True)
df

      ATTORNEY  CLMSEX  CLMINSUR  SEATBELT  CLMAGE    LOSS
0            0     0.0       1.0       0.0    50.0  34.940
1            1     1.0       0.0       0.0    18.0   0.891
2            1     0.0       1.0       0.0     5.0   0.330
3            0     0.0       1.0       1.0    31.0   0.037
4            1     0.0       1.0       0.0    30.0   0.038
...        ...     ...       ...       ...     ...     ...
1083         1     1.0       1.0       0.0    16.0   0.060
1084         0     1.0       1.0       0.0    46.0   3.705
1085         1     1.0       1.0       0.0    39.0   0.099
1086         0     1.0       0.0       0.0     8.0   3.177
1087         1     1.0       1.0       0.0    30.0   0.688

[1088 rows x 6 columns]

In [25]:
x=df.iloc[:,1:]
x

      ATTORNEY  CLMSEX  CLMINSUR  SEATBELT  CLMAGE    LOSS
0            0     0.0       1.0       0.0    50.0  34.940
1            1     1.0       0.0       0.0    18.0   0.891
2            1     0.0       1.0       0.0     5.0   0.330
3            0     0.0       1.0       1.0    31.0   0.037
4            1     0.0       1.0       0.0    30.0   0.038
...        ...     ...       ...       ...     ...     ...
1335         1     0.0       1.0       0.0     NaN   0.576
1336         0     1.0       1.0       0.0    46.0   3.705
1337         1     1.0       1.0       0.0    39.0   0.099
1338         0     1.0       0.0       0.0     8.0   3.177
1339         1     1.0       1.0       0.0    30.0   0.688

[1340 rows x 6 columns]

In [27]:
y=df.iloc[:,0]
y

0           5
1           3
2          66
3          70
4          96
        ...
1335    34100
1336    34110
1337    34113
1338    34145
1339    34153
Name: CASENUM, Length: 1340, dtype: int64

In [28]:
df.corr()

           CASENUM  ATTORNEY    CLMSEX  CLMINSUR  SEATBELT    CLMAGE      LOSS
CASENUM   1.000000  0.011717  0.028151  0.046044 -0.010003 -0.002512 -0.049590
ATTORNEY  0.011717  1.000000  0.079674  0.079439 -0.057189  0.010680 -0.219715
CLMSEX    0.028151  0.079674  1.000000  0.066413 -0.015024 -0.023195 -0.027611
CLMINSUR  0.046044  0.079439  0.066413  1.000000  0.021154  0.049493  0.005821
SEATBELT -0.010003 -0.057189 -0.015024  0.021154  1.000000 -0.027992  0.111189
CLMAGE   -0.002512  0.010680 -0.023195  0.049493 -0.027992  1.000000  0.064612
LOSS     -0.049590 -0.219715 -0.027611  0.005821  0.111189  0.064612  1.000000

In [29]:
y.unique()

array([    5,     3,    66, ..., 34113, 34145, 34153], shape=(1283,))

In [35]:
(y.value_counts()[0]/df.shape[0])*100

np.float64(52.75735294117647)

In [30]:
y.value_counts()

CASENUM
590      3
1010     3
6330     3
5        2
8400     2
        ..
1308     1
1186     1
1150     1
1139     1
34153    1
Name: count, Length: 1283, dtype: int64

In [31]:
from sklearn.model_selection import train_test_split

In [32]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=25,shuffle=True)

In [33]:
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((1072, 6), (268, 6), (1072,), (268,))

In [45]:
from sklearn.linear_model import LogisticRegression

In [47]:
logr=LogisticRegression()#model buliding
logr.fit(x_train,y_train)#model training

LogisticRegression()

In [48]:
y_train_pred=logr.predict(x_train)
y_train_pred

array([0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1,
       1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0,
       0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1,
       0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0,
       0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1,
       1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1,
       1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,
       1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0,
       1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1,
       0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0,
       1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0])

In [49]:
y_test_pred=logr.predict(x_test)
y_test_pred

array([0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1,
       0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0])

In [61]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

In [62]:
#train accuacy
confusion_matrix(y_train,y_train_pred)

array([[317, 151],
       [ 97, 305]])

In [63]:
(317+305)/(317+151+97+305)

0.7149425287356321

In [64]:
accuracy_score(y_train,y_train_pred)

0.7149425287356321

In [65]:
confusion_matrix(y_test,y_test_pred)

array([[74, 32],
       [33, 79]])

In [66]:
accuracy_score(y_test,y_test_pred)

0.7018348623853211

In [67]:
print(classification_report(y_train,y_train_pred))

              precision    recall  f1-score   support

           0       0.77      0.68      0.72       468
           1       0.67      0.76      0.71       402

    accuracy                           0.71       870
   macro avg       0.72      0.72      0.71       870
weighted avg       0.72      0.71      0.72       870

In [68]:
print(classification_report(y_test,y_test_pred))

              precision    recall  f1-score   support

           0       0.69      0.70      0.69       106
           1       0.71      0.71      0.71       112

    accuracy                           0.70       218
   macro avg       0.70      0.70      0.70       218
weighted avg       0.70      0.70      0.70       218