### Car Prediction

In [7]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [8]:
df=pd.read_csv("Cars (1).csv")

In [9]:
df

     HP        MPG  VOL          SP         WT
0    49  53.700681   89  104.185353  28.762059
1    55  50.013401   92  105.461264  30.466833
2    55  50.013401   92  105.461264  30.193597
3    70  45.696322   92  113.461264  30.632114
4    53  50.504232   92  104.461264  29.889149
..  ...        ...  ...         ...        ...
76  322  36.900000   50  169.598513  16.132947
77  238  19.197888  115  150.576579  37.923113
78  263  34.000000   50  151.598513  15.769625
79  295  19.833733  119  167.944460  39.423099
80  236  12.101263  107  139.840817  34.948615

[81 rows x 5 columns]

In [15]:
### Independent and Dependent features
X=df.iloc[:,[0,2,3,4]]
y
y=df.iloc[:,1]
y

0     53.700681
1     50.013401
2     50.013401
3     45.696322
4     50.504232
        ...
76    36.900000
77    19.197888
78    34.000000
79    19.833733
80    12.101263
Name: MPG, Length: 81, dtype: float64

In [19]:
X.head()

   HP  VOL          SP         WT
0  49   89  104.185353  28.762059
1  55   92  105.461264  30.466833
2  55   92  105.461264  30.193597
3  70   92  113.461264  30.632114
4  53   92  104.461264  29.889149

In [17]:
y.head(20)

0     53.700681
1     50.013401
2     50.013401
3     45.696322
4     50.504232
5     45.696322
6     50.013401
7     46.716554
8     46.716554
9     42.299078
10    44.652834
11    39.354094
12    39.354094
13    44.652834
14    45.734893
15    44.652834
16    42.789909
17    39.354094
18    42.789909
19    38.901834
Name: MPG, dtype: float64

In [20]:
### Train Test Split
from sklearn.model_selection import train_test_split

In [22]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0,shuffle=True)
print(X_train,X_test,y_train,y_test)

     HP  VOL          SP         WT
66  165  114  132.484609  37.979956
41   95  106  115.748847  35.027176
3    70   92  113.461264  30.632114
69  245  112  158.300669  37.141733
7    62   50  102.598513  15.847758
..  ...  ...         ...        ...
77  238  115  150.576579  37.923113
67  165  127  133.680223  41.573975
64  150  121  128.128401  40.159482
47   98  103  116.472936  33.910056
44   93  102  114.380966  33.078632

[64 rows x 4 columns]      HP  VOL          SP         WT
22   95  101  120.288996  32.675828
27   92   99  119.105055  32.835069
61  120  116  117.668550  37.860411
13   73   89  111.185353  29.378436
71  162  135  133.415985  44.013139
74  140  129  121.864163  42.618698
30   84  114  113.484609  37.042350
55  130  124  126.404312  40.589068
53  180  113  143.392639  37.620695
26   92  117  120.760520  38.062823
50  115  101  118.288996  33.213954
42  102   92  117.461264  30.527427
48  130   86  127.909442  28.070597
33  102  113  121.392639  37.573290
73  140  160  124.715241  52.997752
2    55   92  105.461264  30.193597
57  115  101  118.288996  32.734518 66    23.103172
41    35.152727
3     45.696322
69    21.273708
7     46.716554
        ...
77    19.197888
67    23.103172
64    23.605158
47    35.052330
44    35.643558
Name: MPG, Length: 64, dtype: float64 22    38.310606
27    38.411003
61    24.609132
13    44.652834
71    23.203569
74    19.086341
30    39.431235
55    27.856252
53    24.487367
26    38.411003
50    29.629936
42    34.070668
48    31.014131
33    36.285456
73    19.086341
2     50.013401
57    29.629936
Name: MPG, dtype: float64

In [23]:
### Implement Random Forest classifier
from sklearn.linear_model import LinearRegression
regression=LinearRegression()
regression.fit(X_train,y_train)

LinearRegression()

In [30]:
#train accuracy
y_train_pred=regression.predict(X_train)
y_train_pred

array([26.76907455, 35.5185244 , 42.43729318, 20.72351304, 48.01323784,
       22.31506788, 16.82973854, 34.35901899, 37.93220542, 41.9173949 ,
       23.34241469, 47.72938564, 26.98217133, 48.49688517, 42.27296995,
       32.39428228, 38.86636219, 36.19993108, 37.01518637, 38.65506402,
       47.31297356, 28.47477195, 39.60746166, 41.48368211, 37.29350077,
       36.37438843, 26.94692489, 42.42263459, 36.78613465, 24.75933295,
       41.77516891, 29.16043044, 37.45265683, 36.02026526, 30.22451347,
       33.75674177, 39.50144821, 37.37575   , 41.11083922, 43.04488023,
       13.21628422, 41.71163356, 42.90906033, 25.62384961, 40.73882633,
       33.7361754 , 38.22504649, 21.85655073, 46.60240947, 38.15695955,
       34.21825937, 35.80498195, 36.76439028, 35.59049207, 39.67147306,
       28.12754298, 39.24186017, 37.15349727, 40.55146033, 18.67313755,
       23.86076354, 26.55980748, 35.69255704, 35.6576828 ])

In [32]:
## Prediction
y_pred=regression.predict(X_test)
y_pred

array([37.3617628 , 38.7074597 , 29.06366575, 41.49794875, 22.51118612,
       24.55153852, 34.58741927, 28.54309907, 27.75729402, 34.91819258,
       33.52564075, 37.74914445, 36.78240263, 34.87940581, 19.32579436,
       42.16439053, 33.07251139])

In [33]:
### Check Accuracy
from sklearn.metrics import r2_score
score=r2_score(y_test,y_pred)
print(score)

0.8012359692731323

In [26]:
score

0.8012359692731323

In [35]:
train_score=r2_score(y_train,y_train_pred)
train_score

0.7567680292415555

In [36]:
regression.predict([[165,114,132.484609,37.979956]])

array([26.76907445])

In [38]:
### Create a Pickle file using serialization 
import pickle
pickle_out = open("mlr.pkl","wb")
pickle.dump(regression, pickle_out)
pickle_out.close()

In [39]:
import numpy as np

In [40]:
regression.predict([[165,114,132.484609,37.979956]])

array([26.76907445])

In [41]:
!pip install streamlit

Requirement already satisfied: streamlit in c:\users\poova\anaconda3\lib\site-packages (1.51.0)
Requirement already satisfied: altair!=5.4.0,!=5.4.1,<6,>=4.0 in c:\users\poova\anaconda3\lib\site-packages (from streamlit) (5.5.0)
Requirement already satisfied: blinker<2,>=1.5.0 in c:\users\poova\anaconda3\lib\site-packages (from streamlit) (1.9.0)
Requirement already satisfied: cachetools<7,>=4.0 in c:\users\poova\anaconda3\lib\site-packages (from streamlit) (5.5.1)
Requirement already satisfied: click<9,>=7.0 in c:\users\poova\anaconda3\lib\site-packages (from streamlit) (8.2.1)
Requirement already satisfied: numpy<3,>=1.23 in c:\users\poova\anaconda3\lib\site-packages (from streamlit) (2.3.5)
Requirement already satisfied: packaging<26,>=20 in c:\users\poova\anaconda3\lib\site-packages (from streamlit) (25.0)
Requirement already satisfied: pandas<3,>=1.4.0 in c:\users\poova\anaconda3\lib\site-packages (from streamlit) (2.3.3)
Requirement already satisfied: pillow<13,>=7.1.0 in c:\users\poova\anaconda3\lib\site-packages (from streamlit) (12.0.0)
Requirement already satisfied: protobuf<7,>=3.20 in c:\users\poova\anaconda3\lib\site-packages (from streamlit) (5.29.3)
Requirement already satisfied: pyarrow<22,>=7.0 in c:\users\poova\anaconda3\lib\site-packages (from streamlit) (21.0.0)
Requirement already satisfied: requests<3,>=2.27 in c:\users\poova\anaconda3\lib\site-packages (from streamlit) (2.32.5)
Requirement already satisfied: tenacity<10,>=8.1.0 in c:\users\poova\anaconda3\lib\site-packages (from streamlit) (9.1.2)
Requirement already satisfied: toml<2,>=0.10.1 in c:\users\poova\anaconda3\lib\site-packages (from streamlit) (0.10.2)
Requirement already satisfied: typing-extensions<5,>=4.4.0 in c:\users\poova\anaconda3\lib\site-packages (from streamlit) (4.15.0)
Requirement already satisfied: watchdog<7,>=2.1.5 in c:\users\poova\anaconda3\lib\site-packages (from streamlit) (4.0.2)
Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in c:\users\poova\anaconda3\lib\site-packages (from streamlit) (3.1.45)
Requirement already satisfied: tornado!=6.5.0,<7,>=6.0.3 in c:\users\poova\anaconda3\lib\site-packages (from streamlit) (6.5.1)
Requirement already satisfied: jinja2 in c:\users\poova\anaconda3\lib\site-packages (from altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (3.1.6)
Requirement already satisfied: jsonschema>=3.0 in c:\users\poova\anaconda3\lib\site-packages (from altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (4.25.0)
Requirement already satisfied: narwhals>=1.14.2 in c:\users\poova\anaconda3\lib\site-packages (from altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (2.7.0)
Requirement already satisfied: colorama in c:\users\poova\anaconda3\lib\site-packages (from click<9,>=7.0->streamlit) (0.4.6)
Requirement already satisfied: gitdb<5,>=4.0.1 in c:\users\poova\anaconda3\lib\site-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.12)
Requirement already satisfied: smmap<6,>=3.0.1 in c:\users\poova\anaconda3\lib\site-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\poova\anaconda3\lib\site-packages (from pandas<3,>=1.4.0->streamlit) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\poova\anaconda3\lib\site-packages (from pandas<3,>=1.4.0->streamlit) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\poova\anaconda3\lib\site-packages (from pandas<3,>=1.4.0->streamlit) (2025.2)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\poova\anaconda3\lib\site-packages (from requests<3,>=2.27->streamlit) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\poova\anaconda3\lib\site-packages (from requests<3,>=2.27->streamlit) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\poova\anaconda3\lib\site-packages (from requests<3,>=2.27->streamlit) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\poova\anaconda3\lib\site-packages (from requests<3,>=2.27->streamlit) (2026.2.25)
Requirement already satisfied: attrs>=22.2.0 in c:\users\poova\anaconda3\lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (25.4.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\users\poova\anaconda3\lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in c:\users\poova\anaconda3\lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (0.37.0)
Requirement already satisfied: rpds-py>=0.7.1 in c:\users\poova\anaconda3\lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (0.28.0)
Requirement already satisfied: six>=1.5 in c:\users\poova\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas<3,>=1.4.0->streamlit) (1.17.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\poova\anaconda3\lib\site-packages (from jinja2->altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (3.0.2)

WARNING: Cache entry deserialization failed, entry ignored

In [42]:
!pip install --upgrade streamlit

Requirement already satisfied: streamlit in c:\users\poova\anaconda3\lib\site-packages (1.51.0)
Collecting streamlit
  Downloading streamlit-1.57.0-py3-none-any.whl.metadata (9.6 kB)
Requirement already satisfied: altair!=5.4.0,!=5.4.1,<7,>=4.0 in c:\users\poova\anaconda3\lib\site-packages (from streamlit) (5.5.0)
Requirement already satisfied: blinker<2,>=1.5.0 in c:\users\poova\anaconda3\lib\site-packages (from streamlit) (1.9.0)
Requirement already satisfied: cachetools<8,>=5.5 in c:\users\poova\anaconda3\lib\site-packages (from streamlit) (5.5.1)
Requirement already satisfied: click<9,>=7.0 in c:\users\poova\anaconda3\lib\site-packages (from streamlit) (8.2.1)
Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in c:\users\poova\anaconda3\lib\site-packages (from streamlit) (3.1.45)
Requirement already satisfied: numpy<3,>=1.23 in c:\users\poova\anaconda3\lib\site-packages (from streamlit) (2.3.5)
Requirement already satisfied: packaging>=20 in c:\users\poova\anaconda3\lib\site-packages (from streamlit) (25.0)
Requirement already satisfied: pandas<4,>=1.4.0 in c:\users\poova\anaconda3\lib\site-packages (from streamlit) (2.3.3)
Requirement already satisfied: pillow<13,>=7.1.0 in c:\users\poova\anaconda3\lib\site-packages (from streamlit) (12.0.0)
Collecting pydeck<1,>=0.8.0b4 (from streamlit)
  Downloading pydeck-0.9.2-py2.py3-none-any.whl.metadata (4.2 kB)
Requirement already satisfied: protobuf<8,>=3.20 in c:\users\poova\anaconda3\lib\site-packages (from streamlit) (5.29.3)
Requirement already satisfied: pyarrow>=7.0 in c:\users\poova\anaconda3\lib\site-packages (from streamlit) (21.0.0)
Requirement already satisfied: requests<3,>=2.27 in c:\users\poova\anaconda3\lib\site-packages (from streamlit) (2.32.5)
Requirement already satisfied: tenacity<10,>=8.1.0 in c:\users\poova\anaconda3\lib\site-packages (from streamlit) (9.1.2)
Requirement already satisfied: toml<2,>=0.10.1 in c:\users\poova\anaconda3\lib\site-packages (from streamlit) (0.10.2)
Requirement already satisfied: typing-extensions<5,>=4.10.0 in c:\users\poova\anaconda3\lib\site-packages (from streamlit) (4.15.0)
Collecting starlette>=0.40.0 (from streamlit)
  Downloading starlette-1.0.0-py3-none-any.whl.metadata (6.3 kB)
Collecting uvicorn>=0.30.0 (from streamlit)
  Downloading uvicorn-0.47.0-py3-none-any.whl.metadata (6.7 kB)
Collecting httptools>=0.6.3 (from streamlit)
  Downloading httptools-0.7.1-cp313-cp313-win_amd64.whl.metadata (3.6 kB)
Requirement already satisfied: anyio>=4.0.0 in c:\users\poova\anaconda3\lib\site-packages (from streamlit) (4.10.0)
Collecting python-multipart>=0.0.10 (from streamlit)
  Downloading python_multipart-0.0.29-py3-none-any.whl.metadata (2.1 kB)
Collecting websockets>=12.0.0 (from streamlit)
  Downloading websockets-16.0-cp313-cp313-win_amd64.whl.metadata (7.0 kB)
Requirement already satisfied: itsdangerous>=2.1.2 in c:\users\poova\anaconda3\lib\site-packages (from streamlit) (2.2.0)
Requirement already satisfied: watchdog<7,>=2.1.5 in c:\users\poova\anaconda3\lib\site-packages (from streamlit) (4.0.2)
Requirement already satisfied: jinja2 in c:\users\poova\anaconda3\lib\site-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (3.1.6)
Requirement already satisfied: jsonschema>=3.0 in c:\users\poova\anaconda3\lib\site-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (4.25.0)
Requirement already satisfied: narwhals>=1.14.2 in c:\users\poova\anaconda3\lib\site-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (2.7.0)
Requirement already satisfied: colorama in c:\users\poova\anaconda3\lib\site-packages (from click<9,>=7.0->streamlit) (0.4.6)
Requirement already satisfied: gitdb<5,>=4.0.1 in c:\users\poova\anaconda3\lib\site-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.12)
Requirement already satisfied: smmap<6,>=3.0.1 in c:\users\poova\anaconda3\lib\site-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\poova\anaconda3\lib\site-packages (from pandas<4,>=1.4.0->streamlit) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\poova\anaconda3\lib\site-packages (from pandas<4,>=1.4.0->streamlit) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\poova\anaconda3\lib\site-packages (from pandas<4,>=1.4.0->streamlit) (2025.2)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\poova\anaconda3\lib\site-packages (from requests<3,>=2.27->streamlit) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\poova\anaconda3\lib\site-packages (from requests<3,>=2.27->streamlit) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\poova\anaconda3\lib\site-packages (from requests<3,>=2.27->streamlit) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\poova\anaconda3\lib\site-packages (from requests<3,>=2.27->streamlit) (2026.2.25)
Requirement already satisfied: sniffio>=1.1 in c:\users\poova\anaconda3\lib\site-packages (from anyio>=4.0.0->streamlit) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\poova\anaconda3\lib\site-packages (from jinja2->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (3.0.2)
Requirement already satisfied: attrs>=22.2.0 in c:\users\poova\anaconda3\lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (25.4.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\users\poova\anaconda3\lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in c:\users\poova\anaconda3\lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (0.37.0)
Requirement already satisfied: rpds-py>=0.7.1 in c:\users\poova\anaconda3\lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (0.28.0)
Requirement already satisfied: six>=1.5 in c:\users\poova\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas<4,>=1.4.0->streamlit) (1.17.0)
Requirement already satisfied: h11>=0.8 in c:\users\poova\anaconda3\lib\site-packages (from uvicorn>=0.30.0->streamlit) (0.16.0)
Downloading streamlit-1.57.0-py3-none-any.whl (9.2 MB)
   ---------------------------------------- 0.0/9.2 MB ? eta -:--:--
   ------------- -------------------------- 3.1/9.2 MB 18.2 MB/s eta 0:00:01
   ----------------------------------- ---- 8.1/9.2 MB 22.0 MB/s eta 0:00:01
   ---------------------------------------- 9.2/9.2 MB 19.2 MB/s  0:00:00
Downloading pydeck-0.9.2-py2.py3-none-any.whl (11.3 MB)
   ---------------------------------------- 0.0/11.3 MB ? eta -:--:--
   ---------------------------- ----------- 8.1/11.3 MB 41.5 MB/s eta 0:00:01
   ---------------------------------------  11.3/11.3 MB 28.3 MB/s eta 0:00:01
   ---------------------------------------- 11.3/11.3 MB 23.7 MB/s  0:00:00
Downloading httptools-0.7.1-cp313-cp313-win_amd64.whl (85 kB)
Downloading python_multipart-0.0.29-py3-none-any.whl (29 kB)
Downloading starlette-1.0.0-py3-none-any.whl (72 kB)
Downloading uvicorn-0.47.0-py3-none-any.whl (71 kB)
Downloading websockets-16.0-cp313-cp313-win_amd64.whl (178 kB)
Installing collected packages: websockets, python-multipart, httptools, uvicorn, starlette, pydeck, streamlit

   ---------------------------------------- 0/7 [websockets]
   ---------------------------------------- 0/7 [websockets]
   ---------------------------------------- 0/7 [websockets]
   ---------------------------------------- 0/7 [websockets]
   ----- ---------------------------------- 1/7 [python-multipart]
   ----------- ---------------------------- 2/7 [httptools]
   ----------------- ---------------------- 3/7 [uvicorn]
   ----------------- ---------------------- 3/7 [uvicorn]
   ----------------- ---------------------- 3/7 [uvicorn]
   ----------------- ---------------------- 3/7 [uvicorn]
   ---------------------- ----------------- 4/7 [starlette]
   ---------------------- ----------------- 4/7 [starlette]
   ---------------------- ----------------- 4/7 [starlette]
   ---------------------- ----------------- 4/7 [starlette]
   ---------------------------- ----------- 5/7 [pydeck]
   ---------------------------- ----------- 5/7 [pydeck]
   ---------------------------- ----------- 5/7 [pydeck]
   ---------------------------- ----------- 5/7 [pydeck]
   ---------------------------- ----------- 5/7 [pydeck]
   ---------------------------- ----------- 5/7 [pydeck]
   ---------------------------- ----------- 5/7 [pydeck]
  Attempting uninstall: streamlit
   ---------------------------- ----------- 5/7 [pydeck]
    Found existing installation: streamlit 1.51.0
   ---------------------------- ----------- 5/7 [pydeck]
   ---------------------------------- ----- 6/7 [streamlit]
   ---------------------------------- ----- 6/7 [streamlit]
   ---------------------------------- ----- 6/7 [streamlit]
   ---------------------------------- ----- 6/7 [streamlit]
   ---------------------------------- ----- 6/7 [streamlit]
   ---------------------------------- ----- 6/7 [streamlit]
   ---------------------------------- ----- 6/7 [streamlit]
    Uninstalling streamlit-1.51.0:
   ---------------------------------- ----- 6/7 [streamlit]
      Successfully uninstalled streamlit-1.51.0
   ---------------------------------- ----- 6/7 [streamlit]
   ---------------------------------- ----- 6/7 [streamlit]
   ---------------------------------- ----- 6/7 [streamlit]
   ---------------------------------- ----- 6/7 [streamlit]
   ---------------------------------- ----- 6/7 [streamlit]
   ---------------------------------- ----- 6/7 [streamlit]
   ---------------------------------- ----- 6/7 [streamlit]
   ---------------------------------- ----- 6/7 [streamlit]
   ---------------------------------- ----- 6/7 [streamlit]
   ---------------------------------- ----- 6/7 [streamlit]
   ---------------------------------- ----- 6/7 [streamlit]
   ---------------------------------- ----- 6/7 [streamlit]
   ---------------------------------- ----- 6/7 [streamlit]
   ---------------------------------- ----- 6/7 [streamlit]
   ---------------------------------- ----- 6/7 [streamlit]
   ---------------------------------- ----- 6/7 [streamlit]
   ---------------------------------- ----- 6/7 [streamlit]
   ---------------------------------- ----- 6/7 [streamlit]
   ---------------------------------- ----- 6/7 [streamlit]
   ---------------------------------- ----- 6/7 [streamlit]
   ---------------------------------- ----- 6/7 [streamlit]
   ---------------------------------- ----- 6/7 [streamlit]
   ---------------------------------- ----- 6/7 [streamlit]
   ---------------------------------- ----- 6/7 [streamlit]
   ---------------------------------- ----- 6/7 [streamlit]
   ---------------------------------- ----- 6/7 [streamlit]
   ---------------------------------- ----- 6/7 [streamlit]
   ---------------------------------- ----- 6/7 [streamlit]
   ---------------------------------- ----- 6/7 [streamlit]
   ---------------------------------- ----- 6/7 [streamlit]
   ---------------------------------- ----- 6/7 [streamlit]
   ---------------------------------- ----- 6/7 [streamlit]
   ---------------------------------- ----- 6/7 [streamlit]
   ---------------------------------- ----- 6/7 [streamlit]
   ---------------------------------- ----- 6/7 [streamlit]
   ---------------------------------- ----- 6/7 [streamlit]
   ---------------------------------- ----- 6/7 [streamlit]
   ---------------------------------- ----- 6/7 [streamlit]
   ---------------------------------- ----- 6/7 [streamlit]
   ---------------------------------- ----- 6/7 [streamlit]
   ---------------------------------- ----- 6/7 [streamlit]
   ---------------------------------- ----- 6/7 [streamlit]
   ---------------------------------- ----- 6/7 [streamlit]
   ---------------------------------- ----- 6/7 [streamlit]
   ---------------------------------- ----- 6/7 [streamlit]
   ---------------------------------- ----- 6/7 [streamlit]
   ---------------------------------- ----- 6/7 [streamlit]
   ---------------------------------------- 7/7 [streamlit]

Successfully installed httptools-0.7.1 pydeck-0.9.2 python-multipart-0.0.29 starlette-1.0.0 streamlit-1.57.0 uvicorn-0.47.0 websockets-16.0

In [43]:
from sklearn.linear_model import Lasso,Ridge

In [44]:
ls = Lasso(alpha=0.01)
ls.fit(X_train,y_train)
y_train_pred_ls = ls.predict(X_train)
y_test_pred_ls = ls.predict(X_test)

In [45]:
r2_score(y_train,y_train_pred_ls)

0.756640423127468

In [46]:
r2_score(y_test,y_test_pred_ls)

0.802967904404088

In [47]:
rd = Ridge(alpha=0.00001)
rd.fit(X_train,y_train)
y_train_pred_rd = rd.predict(X_train)
y_test_pred_rd = rd.predict(X_test)

In [48]:
r2_score(y_train,y_train_pred_rd)

0.7567680292415506

In [49]:
r2_score(y_test,y_test_pred_rd)

0.8012359815803505